### ISSUE TITLE
PyDP does not work in the Docker container

### ISSUE THREAD

**Issue by replomancer** [OpenMined/PyDP#366]
## Description

Importing `pydp` fails inside containers running image built from `Dockerfile`.

## How to Reproduce
Build the image and run the container:
```
docker build -t pydp:test .
docker run -it pydp:test
```

Result of `make test` inside the container:
```
  ValueError

  Directory dist/python_dp-1.0.3-cp39-cp39-linux_x86_64.whl does not exist
```

You can also run `python` inside the container and try this import:
```
>>> import pydp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/PyDP/.venv/lib/python3.9/site-packages/pydp/__init__.py", line 5, in <module>
    from pydp import algorithms
  File "/root/PyDP/.venv/lib/python3.9/site-packages/pydp/algorithms/__init__.py", line 2, in <module>
    from . import laplacian
  File "/root/PyDP/.venv/lib/python3.9/site-packages/pydp/algorithms/laplacian/__init__.py", line 2, in <module>
    from ._bounded_algorithms import BoundedMean
  File "/root/PyDP/.venv/lib/python3.9/site-packages/pydp/algorithms/laplacian/_bounded_algorithms.py", line 2, in <module>
    from .._algorithm import BoundedAlgorithm
  File "/root/PyDP/.venv/lib/python3.9/site-packages/pydp/algorithms/_algorithm.py", line 7, in <module>
    from .._pydp import _algorithms
ModuleNotFoundError: No module named 'pydp._pydp'
```

## System Information
 - OS: Ubuntu
 - OS Version: 20.04
 - Language Version: (default 3.9 from Dockerfile)

**Comment by nadavaviv** [comment]
Also can't seem to use this in a docker container.
This is the error I'm getting:
```
Error: Bad module 'app'

Usage:

    waitress-serve [OPTS] MODULE:OBJECT

Standard options:

    --help
        Show this information.

    --call
        Call the given object to get the WSGI application.

    --host=ADDR
        Hostname or IP address on which to listen, default is '0.0.0.0',
        which means "all IP addresses on this host".

        Note: May not be used together with --listen

    --port=PORT
        TCP port on which to listen, default is '8080'

        Note: May not be used together with --listen

    --listen=ip:port
        Tell waitress to listen on an ip port combination.

        Example:

            --listen=127.0.0.1:8080
            --listen=[::1]:8080
            --listen=*:8080

        This option may be used multiple times to listen on multiple sockets.
        A wildcard for the hostname is also supported and will bind to both
        IPv4/IPv6 depending on whether they are enabled or disabled.

    --[no-]ipv4
        Toggle on/off IPv4 support.

        Example:

            --no-ipv4

        This will disable IPv4 socket support. This affects wildcard matching
        when generating the list of sockets.

    --[no-]ipv6
        Toggle on/off IPv6 support.

        Example:

            --no-ipv6

        This will turn on IPv6 socket support. This affects wildcard matching
        when generating a list of sockets.

    --unix-socket=PATH
        Path of Unix socket. If a socket path is specified, a Unix domain
        socket is made instead of the usual inet domain socket.

        Not available on Windows.

    --unix-socket-perms=PERMS
        Octal permissions to use for the Unix domain socket, default is
        '600'.

    --url-scheme=STR
        Default wsgi.url_scheme value, default is 'http'.

   --url-prefix=STR
        The ``SCRIPT_NAME`` WSGI environment value.  Setting this to anything
        except the empty string will cause the WSGI ``SCRIPT_NAME`` value to be
        the value passed minus any trailing slashes you add, and it will cause
        the ``PATH_INFO`` of any request which is prefixed with this value to
        be stripped of the prefix.  Default is the empty string.

    --ident=STR
        Server identity used in the 'Server' header in responses. Default
        is 'waitress'.

Tuning options:

    --threads=INT
        Number of threads used to process application logic, default is 4.

    --backlog=INT
        Connection backlog for the server. Default is 1024.

    --recv-bytes=INT
        Number of bytes to request when calling socket.recv(). Default is
        8192.

    --send-bytes=INT
        Number of bytes to send to socket.send(). Default is 18000.
        Multiples of 9000 should avoid partly-filled TCP packets.

    --outbuf-overflow=INT
        A temporary file should be created if the pending output is larger
        than this. Default is 1048576 (1MB).

    --outbuf-high-watermark=INT
        The app_iter will pause when pending output is larger than this value
        and will resume once enough data is written to the socket to fall below
        this threshold. Default is 16777216 (16MB).

    --inbuf-overflow=INT
        A temporary file should be created if the pending input is larger
        than this. Default is 524288 (512KB).

    --connection-limit=INT
        Stop creating new channels if too many are already active.
        Default is 100.

    --cleanup-interval=INT
        Minimum seconds between cleaning up inactive channels. Default
        is 30. See '--channel-timeout'.

    --channel-timeout=INT
        Maximum number of seconds to leave inactive connections open.
        Default is 120. 'Inactive' is defined as 'has received no data
        from the client and has sent no data to the client'.

    --[no-]log-socket-errors
        Toggle whether premature client disconnect tracebacks ought to be
        logged. On by default.

    --max-request-header-size=INT
        Maximum size of all request headers combined. Default is 262144
        (256KB).

    --max-request-body-size=INT
        Maximum size of request body. Default is 1073741824 (1GB).

    --[no-]expose-tracebacks
        Toggle whether to expose tracebacks of unhandled exceptions to the
        client. Off by default.

    --asyncore-loop-timeout=INT
        The timeout value in seconds passed to asyncore.loop(). Default is 1.

    --asyncore-use-poll
        The use_poll argument passed to ``asyncore.loop()``. Helps overcome
        open file descriptors limit. Default is False.


There was an exception (ImportError) importing your module.

It had these arguments: 
1. /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.7/site-packages/pydp/_pydp.so)
```

This is my dockerfile:
```
FROM python:3.7.6-buster

RUN apt-get update -y && apt-get install -y python3-dev libstdc++6

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 80

ENTRYPOINT [ "waitress-serve" ]
CMD [ "--call", "app:main" ]
```

Thoughts?

**Comment by nadavaviv** [comment]
I encountered an issue with docker too...
This is what I get when I try to import `pydp` from inside the container
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pydp/__init__.py", line 5, in <module>
    from pydp import algorithms
  File "/usr/local/lib/python3.7/site-packages/pydp/algorithms/__init__.py", line 2, in <module>
    from . import laplacian
  File "/usr/local/lib/python3.7/site-packages/pydp/algorithms/laplacian/__init__.py", line 2, in <module>
    from ._bounded_algorithms import BoundedMean
  File "/usr/local/lib/python3.7/site-packages/pydp/algorithms/laplacian/_bounded_algorithms.py", line 2, in <module>
    from .._algorithm import BoundedAlgorithm
  File "/usr/local/lib/python3.7/site-packages/pydp/algorithms/_algorithm.py", line 7, in <module>
    from .._pydp import _algorithms
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.7/site-packages/pydp/_pydp.so)
```

This is the dockerfile:
```
FROM python:3.7.6-buster

RUN apt-get update -y && apt-get install -y python3-dev libstdc++6

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 80

ENTRYPOINT [ "waitress-serve" ]
CMD [ "--call", "app:main" ]
```

Thoughts?

**Comment by idhamari** [comment]
I have a similar error when trying to install in linux (without docker). 

Probably it would be nice to add instruction to the readme file to show how to install from source. 

             ./prereqs_linux.sh
             ./build_PyDP.sh
             pip install .
             cp src/pydp/_pydp.so ~/.local/lib/python3.10/site-packages/pydp
             #Test
              python -c "import pydp as dp"

> Thoughts?

I would try to run the command from the Dockerfile manually inside the Docker container and check which one has error. e.g. this link is missing 

            ARG BAZELISK_DOWNLOAD_URL=https://github.com/bazelbuild/bazelisk/releases/download/ 

and should be replaced by something like
  
           ARG BAZELISK_DOWNLOAD_URL=https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64


In my case, I modified the result in _get_python_include function in this file ~/.cache/bazel/_bazel_user/3738acce07ef18f8aca7932bae86e827/external/pybind11_bazel/python_configure.bzl


                def _get_python_include(repository_ctx, python_bin):
                    """Gets the python include path."""

                    result = _execute(
                        repository_ctx,
                        [
                            python_bin,
                            "-c",
                            "from __future__ import print_function; import sysconfig; print(sysconfig.get_paths()['include'])",
                        ],

                        error_msg = "Problem getting python include path.",
                        error_details = ("Is the Python binary path set up right? " +
                                        "(See ./configure or " + _PYTHON_BIN_PATH + ".) " +
                                        "Is distutils installed?"),
                    )
                    return result.stdout.splitlines()[0]

I also solve the issue by updating the WORKSPACE file to use the recent library:

            http_archive(
                  name = "pybind11_bazel",
                  #strip_prefix = "pybind11_bazel-26973c0ff320cb4b39e45bc3e4297b82bc3a6c09",
                  #urls = ["https://github.com/pybind/pybind11_bazel/archive/26973c0ff320cb4b39e45bc3e4297b82bc3a6c09.zip"],
               strip_prefix = "pybind11_bazel-master",
                 urls = ["https://github.com/pybind/pybind11_bazel/archive/refs/heads/master.zip"],
               )
